version: 2

updates:
- package-ecosystem: npm
  directory: /
  versioning-strategy: increase-if-necessary
  schedule:
    interval: weekly
  production-dependencies:
    dependency-type: "production"
  development-dependencies:
    dependency-type: "development"
